class Error(Exception):
		pass

class DuplicateError(Error):
		pass
